# 玩家進入時訊息
Welcome_MSG: " 進入了 工程測試區!"
# Shift + F後執行的指令
ShiftF_CMD: "help"
# SetHome上限
Home_Limit: 5

BalanceTopTimerInterval: 1200

currencyNameSingular: "Dollar"
currencyNamePlural: "Dollars"

locale: "en-US"

mysql:
  use-mysql: true
  host: "192.168.0.126"
  port: 3306
  database: "Mist_plugin"
  username: "mist_plugin"
  password: "Chen_gom86660720"

customSymbolEnabled: false
customSymbol: ""

startingBalance: 0.0
# 方便記數
suffixes:
  k: 3
  K: 3
  m: 6
  M: 6
  b: 9
  B: 9
  t: 12
  T: 12
  q: 15
  Q: 15

# 訊息Lang
messages:
  prefix: "&b[&r&c系統&r&b]"
  noPermission:
    - "%prefix% &c你沒有權限那樣做"
  playersOnly:
    - "%prefix% &c只有玩家才能此執行命令"
  notVIP:
    - "%prefix% &c你不是VIP"

  balance:
    usage:
      - "%prefix% &e/balance"
      - "%prefix% &e/balance {player}"
    noAccount:
      - "%prefix% &c找不到玩家"
    balance:
      - "%prefix% &6目前金錢餘額 &a%balance%"
    otherNoAccount:
      - "%prefix% &c找不到 &e%player%"
    otherBalance:
      - "%prefix% &e%player% &6的金錢餘額 &a%balance%"

  money:
    give:
      usage:
        - "%prefix% &e/money give {player} {amount}"
      otherDoesntExist:
        - "%prefix% &e%player% &c不存在"
      otherNoAccount:
        - "%prefix% &c找不到玩家"
      invalidAmount:
        - "%prefix% &c新增失敗"
      sent:
        - "%prefix% &6已新增 &a%amount% &6給 &e%player%"
      sentMultiple:
        - "%prefix% &6已新增 &a%amount% &6給 &e%player%"
      received:
        - "%prefix% &6你得到了 &a%amount%&a"

    help:
      usage:
        - "%prefix% &e/money help"
      message:
        - "%prefix% &eCommands:"
        - "%prefix% &b/money help"
        - "%prefix% &b/balancetop"
        - "%prefix% &b/balance"
        - "%prefix% &b/balance {player}"
        - "%prefix% &b/pay {player} {amount}"

    reload:
      usage:
        - "%prefix% &e/money reload"
      reloaded:
        - "%prefix% &b重新載入完成"

    set:
      usage:
        - "%prefix% &e/money set {player} {amount}"
      otherDoesntExist:
        - "%prefix% &e%player% &c不存在"
      otherNoAccount:
        - "%prefix% &c找不到玩家"
      invalidAmount:
        - "%prefix% &c設定失敗"
      setter:
        - "%prefix% &6已設定 &a%player% &6的金錢為 &e%balance%"
      setterMultiple:
        - "%prefix% &6已設定 &a%total% &6位玩家的金錢為 &e%balance%"
      set:
        - "%prefix% &6你的金錢已被設定為 &a%amount%"

    take:
      usage:
        - "%prefix% &c/money take {player} {amount}"
      otherDoesntExist:
        - "%prefix% &e%player% &c不存在"
      otherNoAccount:
        - "%prefix% &c找不到玩家"
      invalidAmount:
        - "%prefix% &c扣除失敗"
      take:
        - "%prefix% &6已從 &e%player% &6扣除 &a%amount%"
      takeMultiple:
        - "%prefix% &6已設定 &a%total% &6位玩家的金錢為 &e%balance%"
      taken:
        - "%prefix% &6你被扣除了 &a%amount%"

    pay:
      usage:
        - "%prefix% &c/pay {player} {amount}"
      otherDoesntExist:
        - "%prefix% &e%player% &c不存在"
      noAccount:
        - "%prefix% &c你沒有帳戶資料"
      otherNoAccount:
        - "%prefix% &c找不到玩家"
      cannotPaySelf:
        - "%prefix% &c你不能支付自己金錢"
      invalidAmount:
        - "%prefix% &c支付失敗"
      paid:
        - "%prefix% &6已支付 &a%amount% &6給 &e%player%"
      received:
        - "%prefix% &6已收到 &e%player% 支付的 &a%amount%"

    top:
      usage:
        - "%prefix% &c/balancetop"
        - "%prefix% &c/balancetop {number}"
      noAccounts:
        - "%prefix% &c沒有玩家"
      invalidTop:
        - "%prefix% &c無效指令"
      notEnoughPlayers:
        - "%prefix% &c沒有足夠的玩家"
      messageHeader:
        - "&6-----&b&lMist Cabin &r&e金錢榜&6-----"
      message:
        - "&b%rank%. &e%player%: &a%balance%"
      self:
        - "%prefix% &b%rank%. &e%player%: &e%balance% (YOU)"

  setspawn:
    usage:
      - "%prefix% &e/setspawn"
    successful:
      - "%prefix% &e設置成功 &6Spawn座標為: &b%X%&6, &b%Y%&6, &b%Z%"
    fail:
      - "%prefix% &cSpawn設置失敗"

  delspawn:
    usage:
      - "%prefix% &e/delspawn"
    successful:
      - "%prefix% &eSpawn刪除成功"
    fail:
      - "%prefix% &cSpawn刪除失敗"

  spawn:
    usage:
      - "%prefix% &e/spawn"
    successful:
      - "%prefix% &e已傳送至Spawn"
    teleport:
      - "%prefix% &e你被傳送至Spawn"
    noLocation:
      - "%prefix% &c沒有設置Spawn"

  home:
    successful:
      - "%prefix% &6已傳送至家 &e%home%"
    failed:
      - "%prefix% &c傳送失敗"
    notFound:
      - "%prefix% &c未找到家"

  sethome:
    usage:
      - "%prefix% &e/sethome {name}"
    limitExceeded:
      - "%prefix% &c家數量已達上限"
    successful:
      - "%prefix% &e%home% &6家已設定成功 座標: &b%X%&6, &b%Y%&6, &b%Z%"
    failed:
      - "%prefix% &c設定失敗"

  delhome:
    usage:
      - "%prefix% &e/delhome {name}"
    successful:
      - "%prefix% &6已刪除家 &e%home%"
    failed:
      - "%prefix% &c刪除失敗"
    notFound:
      - "%prefix% &c未找到家"

  tp:
    tpaUsage:
      - "%prefix% &e/tpa {player}"
    tpaHereUsage:
      - "%prefix% &e/tpahere {player}"
    tpaAcceptUsage:
      - "%prefix% &e/tpaaccept"
    tpaCancelUsage:
      - "%prefix% &e/tpacancel"
    tpaHereAcceptUsage:
      - "%prefix% &e/tpahereaccept"
    tpaHereCancelUsage:
      - "%prefix% &e/tpaherecancel"
    tpaSendRequest:
      - "%prefix% &6已對 &e%player% &6發送傳送請求"
    tpaReceiveRequest:
      - "%prefix% &e%player% 發送傳送請求 &e到你身邊"
    tpaHereSendRequest:
      - "%prefix% &6已對 &e%player% &6發送傳送請求"
    tpaHereReceiveRequest:
      - "%prefix% &e%player% &6發送傳送請求 &e到他身邊"
    acceptRequest:
      - "%prefix% &6你&a接受&6了傳送請求"
    cancelRequest:
      - "%prefix% &6你&a拒絕&6了傳送請求"
    successfulTeleport:
      - "%prefix% &6傳送成功"
    requestNotFound:
      - "%prefix% &e未找到傳送請求"
    playerNotOnline:
      - "%prefix% &e找不到玩家"

  back:
    usage:
      - "%prefix% &e/back"
    successful:
      - "%prefix% &6傳送成功"
    failed:
      - "%prefix% &6傳送失敗"
    notFound:
      - "%prefix% &e找不到地點"

  homeVIP:
    usage:
      - "%prefix% &e/homevip {家名稱} {方塊ID}"
    invalid:
      - "%prefix% &c無效方塊ID"
    successful:
      - "%prefix% &6成功設置家 &9%homename% &6的方塊ID為 &e%blockID%"
    failed:
      - "%prefix% &c設置失敗"

  setwarp:
    usage:
      - "%prefix% &e/setwarp {name}"
    successful:
      - "%prefix% &6設置成功 &e%name% &6座標為 &b%X%&6, &b%Y%&6, &b%Z%"
    failed:
      - "%prefix% &c設置失敗"

  delwarp:
    usage:
      - "%prefix% &e/delwarp {name}"
    successful:
      - "%prefix% &6已刪除Warp &e%name%"
    failed:
      - "%prefix% &c刪除失敗"
    notFound:
      - "%prefix% &c未找到Warp"

  warp:
    usage:
      - "%prefix% &e/warp {name}"
    successful:
      - "%prefix% &6已傳送至Warp %e%name%"
    failed:
      - "%prefix% &c傳送失敗"
    notFound:
      - "%prefix% &c未找到Warp"

  ban:
    usage:
      - "%prefix% &e/ban {player_name} {reason}"
    playerNotFound:
      - "%prefix% &c沒有找到玩家"
    success:
      - "%prefix% &6玩家 &e%player% &6已經被BAN了\n原因: %reason%"
  tempban:
    usage:
      - "%prefix% &e/tempban {time} {player_name} {reason}"
    invalied:
      - "%prefix% &c指令失敗"
    playerNotFound:
      - "%prefix% &c沒有找到玩家"
    success:
      "%prefix% &c玩家 &e%player% &6已經被TEMPBAN了\n原因: %reason%"
  unban:
    usage:
      - "%prefix% &e/unban {player}"
    playerNotfound:
      - "%prefix% &c沒有找到玩家"
    success:
      - "%prefix% &e%player% 已經被UNBAN了"
  hat:
    usage:
      - "%prefix% &e/hat"
    airHand:
      - "%prefix% &c手上要有物品!"
    success:
      - "%prefix% &6已將 %material% 戴在頭上!"