# 玩家進入時訊息
Welcome_MSG: "歡迎進入 工程測試區!"
# Shift + F後執行的指令
ShiftF_CMD: "help"
# SetHome上限
Home_Limit: 5

BalanceTopTimerInterval: 1200

currencyNameSingular: "Dollar"
currencyNamePlural: "Dollars"

locale: "en-US"

mysql:
  use-mysql: true
  host: "192.168.0.126"
  port: 3306
  database: "Mist_plugin"
  username: "mist_plugin"
  password: "Chen_gom86660720"

customSymbolEnabled: false
customSymbol: ""

startingBalance: 0.0
# 方便記數
suffixes:
  k: 3
  K: 3
  m: 6
  M: 6
  b: 9
  B: 9
  t: 12
  T: 12
  q: 15
  Q: 15

# 訊息Lang
messages:
  prefix: "&b[&r&6Mist plugin&r&b]"
  noPermission:
    - "%prefix% &c你沒有權限那樣做"
  playersOnly:
    - "%prefix% &c只有玩家才能此執行命令"

  balance:
    usage:
      - "%prefix% &cUsage: /balance"
      - "%prefix% &cUsage: /balance {player}"
    noAccount:
      - "%prefix% &c找不到玩家"
    balance:
      - "%prefix% &a目前金錢餘額 &e%balance%"
    otherNoAccount:
      - "%prefix% &c找不到 &5%player%"
    otherBalance:
      - "%prefix% &5%player% &a的金錢餘額 &e%balance%"

  money:
    invalidSubCommand:
      - "%prefix% &cThat sub-command doesn't exist!"

    give:
      usage:
        - "%prefix% &cUsage: /money give {player} {amount}"
      otherDoesntExist:
        - "%prefix% &5%player% &cdoesn't exist!"
      otherNoAccount:
        - "%prefix% &c找不到玩家"
      invalidAmount:
        - "%prefix% &c新增失敗"
      sent:
        - "%prefix% &a已新增 &e%amount% &a給 &5%player%"
      sentMultiple:
        - "%prefix% &a已新增 &e%amount% &a給 &b%player%"
      received:
        - "%prefix% &a你得到了 &e%amount%&a"

    help:
      usage:
        - "%prefix% &cUsage: /money help"
      message:
        - "%prefix% &eCommands:"
        - "%prefix% &b/money help"
        - "%prefix% &b/balancetop"
        - "%prefix% &b/balance"
        - "%prefix% &b/balance {player}"
        - "%prefix% &b/pay {player} {amount}"

    reload:
      usage:
        - "%prefix% &cUsage: /money reload"
      reloaded:
        - "%prefix% &aYou reloaded the economy."

    set:
      usage:
        - "%prefix% &cUsage: /money set {player} {amount}"
      otherDoesntExist:
        - "%prefix% &5%player% &cdoesn't exist!"
      otherNoAccount:
        - "%prefix% &c找不到玩家"
      invalidAmount:
        - "%prefix% &c設定失敗"
      setter:
        - "%prefix% &a已設定 &5%player% &a的金錢為 &e%balance%"
      setterMultiple:
        - "%prefix% &b%total% players' balances were set to &e%balance%&a."
      set:
        - "%prefix% &aYour balance was set to &e%amount%&a."

    take:
      usage:
        - "%prefix% &cUsage: /money take {player} {amount}"
      otherDoesntExist:
        - "%prefix% &5%player% &cdoesn't exist!"
      otherNoAccount:
        - "%prefix% &c找不到玩家"
      invalidAmount:
        - "%prefix% &c扣除失敗"
      insufficientFunds:
        - "%prefix% &5%player% &chas insufficient funds!"
      take:
        - "%prefix% &a從 &5%player% &a扣除 &e%amount%"
      takeMultiple:
        - "%prefix% &e%amount% &awas taken from &b%total% &aplayers' accounts."
      taken:
        - "%prefix% &a你被扣除了 &e%amount%"

    pay:
      usage:
        - "%prefix% &cUsage: /pay {player} {amount}"
      otherDoesntExist:
        - "%prefix% &5%player% &cdoesn't exist!"
      noAccount:
        - "%prefix% &c你沒有帳戶資料"
      otherNoAccount:
        - "%prefix% &c找不到玩家"
      cannotPaySelf:
        - "%prefix% &c你不能支付自己金錢"
      invalidAmount:
        - "%prefix% &c支付失敗"
      insufficientFunds:
        - "%prefix% &cYou have insufficient funds!"
      paid:
        - "%prefix% &a已支付 &e%amount% &a給 &5%player%"
      received:
        - "%prefix% &a已收到 &5%player% 支付的 &e%amount%"

    top:
      usage:
        - "%prefix% &cUsage: /balancetop"
        - "%prefix% &cUsage: /balancetop {number}"
      noAccounts:
        - "%prefix% &c沒有玩家"
      invalidTop:
        - "%prefix% &c無效指令"
      notEnoughPlayers:
        - "%prefix% &c沒有足夠的玩家"
      message:
        - "%prefix% &b%rank%. &a%player%: &b%balance%"
      self:
        - "%prefix% &b%rank%. &a%player%: &b%balance% (YOU)"

  setspawn:
    usage:
      - "%prefix% &6/setspawn 創建伺服器Spawn"
    successful:
      - "%prefix% &6Spawn設置成功!"
    fail:
      - "%prefix% &cSpawn設置失敗"

  delspawn:
    usage:
      - "%prefix% &6/delspawn 刪除伺服器Spawn"
    successful:
      - "%prefix% &6Spawn刪除成功!"
    fail:
      - "%prefix% &cSpawn刪除失敗"

  spawn:
    usage:
      - "%prefix% &6/spawn"
    successful:
      - "%prefix% &6傳送成功"
    teleport:
      - "%prefix% &6你被傳送至Spawn"
    noLocation:
      - "%prefix% &c沒有設置Spawn"

  home:
    successful:
      - "%prefix% &6傳送成功"
    failed:
      - "%prefix% &c傳送失敗"
    notFound:
      - "%prefix% &c未找到家"

  sethome:
    usage:
      - "%prefix% &6/sethome <Home name>"
    limitExceeded:
      - "%prefix% &c家數量已達上限"
    successful:
      - "%prefix% &6設定成功"
    failed:
      - "%prefix% &c設定失敗"

  delhome:
    usage:
      - "%prefix% &6/delhome <Home name>"
    successful:
      - "%prefix% &6刪除成功"
    failed:
      - "%prefix% &c刪除失敗"
    notFound:
      - "%prefix% &c未找到家"

  tp:
    tpaUsage:
      - "%prefix% &6/tpa <player>"
    tpaHereUsage:
      - "%prefix% &6/tpahere <player>"
    tpaAcceptUsage:
      - "%prefix% &6/tpaaccept"
    tpaCancelUsage:
      - "%prefix% &6/tpacancel"
    tpaSendRequest:
      - "%prefix% &6已發送傳送請求"
    tpaReceiveRequest:
      - "%prefix% &6%name% 發送傳送請求 到你身邊"
    tpaHereSendRequest:
      - "%prefix% &6已發送傳送請求"
    tpaHereReceiveRequest:
      - "%prefix% &6%name% 發送傳送請求 到他身邊"
    acceptRequest:
      - "%prefix% &6你接受了傳送請求"
    cancelRequest:
      - "%prefix% &6你拒絕了傳送請求"
    successfulTeleport:
      - "%prefix% &6傳送成功"
    requestNotFound:
      - "%prefix% &e未找到傳送請求"
    playerNotOnline:
      - "%prefix% &e找不到玩家"

  back:
    usage:
      - "%prefix% &6/back"
    successful:
      - "%prefix% &6傳送成功"
    failed:
      - "%prefix% &6傳送失敗"
    notFound:
      - "%prefix% &e找不到地點"