name: MistPlugin
version: '${version}'
main: com.chenyue.mistplugin.MistPlugin
api-version: '1.20'
description: Mist Cabin Plugin
author: ChenYue
website: 'https://github.com/ChenYueTW/Mist-plugin'

commands:
  eco:
    aliases:
      - economy
  mist:
    description: mist Command
  balance:
    aliases:
      - bal
      - money
  balancetop:
    aliases:
      - baltop
  pay:
    description: pay

