name: MistPlugin
version: '${version}'
main: com.chenyue.mistplugin.MistPlugin
api-version: '1.20'
description: Mist Cabin Plugin
author: ChenYue
website: 'https://github.com/ChenYueTW/Mist-plugin'
depend:
  - PlaceholderAPI

commands:
  eco:
    aliases:
      - economy
  mist:
    description: mist Command
  balance:
    aliases:
      - bal
      - money
  balancetop:
    aliases:
      - baltop
  pay:
    description: pay
  spawn:
    description: spawn
  setspawn:
    description: setSpawn
  delspawn:
    description: delSpawn
  home:
    description: home
  sethome:
    description: sethome
  delhome:
    description: delhome
  tpa:
    description: tpa
  tpahere:
    description: tpahere
  tpaaccept:
    description: tpaAccept
  tpacancel:
    description: tpaCancel
  tpahereaccept:
    description: tpaHereAccept
  tpaherecancel:
    description: tpaHereCancel
  back:
    description: back
  homevip:
    description: Home VIP
  setwarp:
    description: Set warp
  delwarp:
    description: Delete warp
  warp:
    description: tp to warp
  ban:
    description: ban Player
  tempban:
    description: tempban Player
  unban:
    description: unBan Player
  hat:
    description: hat
  suicide:
    description: suicide
  workbench:
    description: Workbench
  enderchest:
    description: EncoderChest
  fly:
    description: fly

permissions:
  mist.command.balance:
    default: true
  mist.command.balancetop:
    default: true
  mist.command.pay:
    default: true
  mist.command.eco:
    default: op
  mist.command.spawn:
    default: true
  mist.command.setspawn:
    default: op
  mist.command.delspawn:
    default: op
  mist.command.home:
    default: true
  mist.command.sethome:
    default: true
  mist.command.delhome:
    default: true
  mist.command.tpa:
    default: true
  mist.command.tpahere:
    default: true
  mist.command.tpaaccept:
    default: true
  mist.command.tpacancel:
    default: true
  mist.command.tpahereaccept:
    default: true
  mist.command.tpaherecancel:
    default: true
  mist.command.back:
    default: true
  mist.command.vip:
    default: false
  mist.command.setwarp:
    default: false
  mist.command.delwarp:
    default: false
  mist.command.warp:
    default: true
  mist.command.ban:
    default: op
  mist.command.tempban:
    default: op
  mist.command.unban:
    default: op
  mist.command.suicide:
    default: true
  mist.command.fly:
    default: op